openapi: 3.0.1
info:
  title: VirtualEC 管理機能API
  version: 0.0.1
servers:
  - url: /api
paths:
  /products:
    get:
      operationId: productSearch
      tags:
        - product
      description: |
        Productの検索を行う
      parameters:
        - name: name
          in: query
          required: false
          description: Product名の前方一致検索をする
          schema:
            type: string
            example: product
      responses:
        200:
          $ref: "#/components/responses/ProductSearchSuccess"
        500:
          $ref: "#/components/responses/ServerError"
    post:
      operationId: productCreate
      tags:
        - product
      description: |
        Productを新規作成する
      requestBody:
        $ref: "#/components/requestBodies/ProductCreate"
      responses:
        201:
          $ref: "#/components/responses/ProductCreateSuccess"
        500:
          $ref: "#/components/responses/ServerError"

  /products/{product_id}:
    get:
      operationId: productGet
      tags:
        - product
      description: |
        Productの詳細情報を取得する
      parameters:
        - name: product_id
          in: path
          required: true
          description: ProductのID
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        200:
          $ref: "#/components/responses/ProductGetSuccess"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/ServerError"

components:
  requestBodies:
    ProductCreate:
      description: "作成するProductの情報"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Product"
  responses:
    ProductSearchSuccess:
      description: "検索成功"
      content:
        application/json:
          schema:
            type: object
            required:
              - products
            properties:
              products:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
    ProductSearchFailed:
      description: "検索失敗"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    ProductGetSuccess:
      description: "成功"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Product"
    ProductCreateSuccess:
      description: "成功"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Product"
    NotFound:
      description: "Not Found"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    ServerError:
      description: "Server Error"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  schemas:
    Product:
      type: object
      required:
        - id
        - name
        - price
      properties:
        id:
          type: integer
          format: int64
          example: 1
          readOnly: true
        name:
          type: string
          example: product
        price:
          type: integer
          format: int64
          example: 100
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: エラーが発生しました
        details:
          type: array
          items:
            type: string
