# https://taskfile.dev

version: "2"

tasks:
  test:
    desc: "テスト実行"
    cmds:
      - go test -cover ./...
    sources:
      - "./**/*.go"
  build_devenv:
    desc: "開発環境Dockerイメージのビルド"
    cmds:
      - .develop/build.sh
