# https://taskfile.dev

version: "2"

tasks:
  test:
    desc: "テスト実行"
    cmds:
      - go test -cover ./domain/... ./infrastructure/... ./usecase/... ./lib/...
    sources:
      - "domain/**/*.go"
      - "infrastructure/**/*.go"
      - "usecase/**/*.go"
      - "lib/**/*.go"

  integration_test:
    desc: "インテグレーションテスト実行"
    cmds:
      - ./script/integration_test.sh
    env:
      DATASTORE_EMULATOR_HOST: localhost:1234

  build_devenv:
    desc: "開発環境Dockerイメージのビルド"
    cmds:
      - .develop/build.sh

  format:
    desc: "コードフォーマットを実行する"
    cmds:
      - goimports -w -l ./

  openapi:
    desc: "OpenAPIを利用したコード生成"
    cmds:
      - rm -f ./adapter/rest/admin/api_gen.go ./adapter/rest/admin/api_type_gen.go
      - oapi-codegen -generate chi-server -package admin ./documents/admin/openapi.yaml > ./adapter/rest/admin/api_gen.go
      - oapi-codegen -generate types -package admin ./documents/admin/openapi.yaml > ./adapter/rest/admin/api_type_gen.go
      - task: format
