# https://taskfile.dev

version: "2"

tasks:
  test:
    desc: "テスト実行"
    cmds:
      - go test -cover ./adapter/... ./domain/... ./infrastructure/... ./usecase/... ./pkg/...
    sources:
      - "adapter/**/*.go"
      - "domain/**/*.go"
      - "infrastructure/**/*.go"
      - "usecase/**/*.go"
      - "pkg/**/*.go"

  integration_test:
    desc: "インテグレーションテスト実行"
    cmds:
      - ./script/integration_test.sh
    env:
      DATASTORE_EMULATOR_HOST: localhost:1234

  build_devenv:
    desc: "開発環境Dockerイメージのビルド"
    cmds:
      - .develop/build.sh

  format:
    desc: "コードフォーマットを実行する"
    cmds:
      - goimports -w -l ./

  generate:
    desc: "go generateを実行する"
    cmds:
      - rm -f ./adapter/rest/admin/internal/openapi_gen.go
      - go generate ./...
      - task: format
