// Package admin provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package admin

// Error defines model for Error.
type Error struct {
	Details *[]string `json:"details,omitempty"`
	Message string    `json:"message"`
}

// Product defines model for Product.
type Product struct {
	Id    int64  `json:"id"`
	Name  string `json:"name"`
	Price int64  `json:"price"`
}

// ProductGetFailed defines model for ProductGetFailed.
type ProductGetFailed Error

// ProductGetNotFound defines model for ProductGetNotFound.
type ProductGetNotFound Error

// ProductGetSuccess defines model for ProductGetSuccess.
type ProductGetSuccess Product

// ProductSearchFailed defines model for ProductSearchFailed.
type ProductSearchFailed Error

// ProductSearchSuccess defines model for ProductSearchSuccess.
type ProductSearchSuccess struct {
	Products []Product `json:"products"`
}

// ProductSearchParams defines parameters for ProductSearch.
type ProductSearchParams struct {

	// Product名の前方一致検索をする
	Name *string `json:"name,omitempty"`
}
