// Code generated by interfacer; DO NOT EDIT

package firestore

import (
)

// Cursor is an interface generated for "cloud.google.com/go/datastore.Cursor".
type Cursor interface {
	String() string
}
