// Code generated by interfacer; DO NOT EDIT

package firestore

import (
	"cloud.google.com/go/datastore"
)

// Iterator is an interface generated for "cloud.google.com/go/datastore.Iterator".
type Iterator interface {
	Cursor() (datastore.Cursor, error)
	Next(interface{}) (*datastore.Key, error)
}
